superuser:
	docker exec -it fut21-web ./manage.py createsuperuser

shell:
	docker exec -it fut21-web ./manage.py shell

makemigrations:
	docker exec -it fut21-web ./manage.py makemigrations

migrate:
	docker exec -it fut21-web ./manage.py migrate

showmigrations:
	docker exec -it fut21-web ./manage.py showmigrations
